### ISSUE TITLE
script not working

### ISSUE THREAD

**Issue by arwystli** [khromov/dropbox-public-folder-replacement#1]
I have followed the instructions carefully but I am having no luck in getting this to work. All I get is errorcode 500, tried it in browser and using wget

**Comment by khromov** [comment]
Hey @arwystli 

Could you enable PHP errors. Just drop the following block of code  after the line containing `namespace` in  `index.php`:

```
error_reporting(E_ALL);
ini_set('display_errors', 1);
```

The error should provide some guidance as to what is going wrong, so please post it here.

**Comment by arwystli** [comment]
After lots of messing around, I decide to abandon The Errordocument directive for apache, (using Apache 2.4.x here) and use mod_rewrite instead:

`<IfModule mod_rewrite.c>`
`  RewriteEngine on`
`  RewriteCond %{REQUEST_FILENAME} !-f`
`  RewriteCond %{REQUEST_FILENAME} !-d`
`  RewriteCond %{REQUEST_URI} !=/favicon.ico`
`  RewriteRule ^(.*)$ index.php?q=$1 [L,QSA]`
`</IfModule>`

This worked straightaway. 
`$_SERVER['REQUEST_URI']` still has the filename with path and `$_SERVER['QUERY_STRING']` has the filename as the value to the query variable 'q' but this can be ignored.
I also was able to fetch the content with `file_get_content()` and `stream_get_content()`

**Comment by khromov** [comment]
@arwystli Happy you got it to work! Feel free to make a pull request if you want to improve the documentation.

**Comment by khromov** [comment]
@arwystli The reason I didn't use `file_get_content()` is because it downloads the entire file into memory before sending it. I wanted to be able to transfer large files without keeping the entire file in memory, which could result in an out-of-memory error and also delay the downloading of the file. I think this **should** be possible with `stream_get_content()` but I couldn't get it to work. Just a heads up!

**Comment by arwystli** [comment]
@khromov I agree that `file_get_content` might bog down with large files, the existing method is fine.
I am willing to add code to the .htaccess file and mod the README.md, I have not done a pull request of github before, the docs suggest that this needs to be done on a branch and I see no immediate way of making one so perhaps you need to make a suitable branch for me to commit to. Let me know what is the best way.

**Comment by khromov** [comment]
@arwystli If you just to improve the documentation, you can just edit the file online, which will create a new branch automagically.

![screen shot 2017-09-14 at 14 28 37](https://user-images.githubusercontent.com/1207507/30429789-0c36bee6-9959-11e7-84bf-74fcc393d695.png)

You can read more about pull requests here:
https://help.github.com/articles/about-pull-requests/

**Comment by arwystli** [comment]
Edited README.md and done pull request.

**Comment by khromov** [comment]
PR merged. Thanks again!
